### ISSUE TITLE
Add UI testing

### ISSUE THREAD

**Issue by frederikdesmedt** [datarootsio/cheek#13]
Currently there aren't any tests for the UI, we should build some.

Because the UI is terminal-based we could quite easily do UI testing as follows:
- Set up the UI in the testing environment (can be headless)
- Send the appropriate keystrokes to stdin (depending on what you want to test)
- Look at the `model` to assert things

And then we can also just add unit tests on functions that don't depend on the UI, such as `getTitle`, `runWindow`, `view` and such

**Comment by Bart6114** [comment]
Well it's not that easy actually.  I've tried this. From the moment you run this headless it won't starting, complaining that it doesn't have access to a TTY. At least on OSX that was the case. Haven't looked into it further though.

**Comment by Bart6114** [comment]
And yes, the coverage gap annoys me as well. Especially when people start decreasing coverage #15   👉 @frederikdesmedt 👈

**Comment by frederikdesmedt** [comment]
Tsss, such finger pointing ;)

How about we just apply the Elm Architecture approach directly within the tests? For example, we could test whether ctrl+c properly exits the program by using something like:

```
func TestQuitOnCtrlQ(t *testing.T) {
  m := initializeModel(...)
  m.Init()
  _, cmd := m.Update(tea.KeyCtrlC)
  assert.Equal(t, tea.Quit(), cmd())
}
```

**Comment by Bart6114** [comment]
If that works it would def be cleanest.
That way we can also just call `.View()` to get what is shown on screen.

**Comment by Bart6114** [comment]
initial stub added, closing for now
