### ISSUE TITLE
do not show status dot when no runs have occurred yet

### ISSUE THREAD

**Issue by bart6114** [datarootsio/cheek#231]
See content of red doodled circle.

![image](https://github.com/user-attachments/assets/40df3c55-1cd4-4189-951b-0cac56bb2c98)

**Comment by alaGarbey675** [comment]
<img width="961" alt="image" src="https://github.com/user-attachments/assets/2c84de43-42f0-414f-870b-9504effe91f3">

It's fixed; I just added a condition to prevent showing the bullet point status when there is no history.
